apiVersion: apps/v1
kind: Deployment
metadata:
 name: gunicorn-deployment-dev
 namespace: cdh-dev
spec:
 selector:
   matchLabels:
    type: web
 replicas: 1
 template:
   metadata:
     labels:
       type: web
   spec:
    containers:
    - name: container
      image: cis07385/back:latest
      command: ["/bin/sh", "-ec", "python manage.py makemigrations && python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:8000"]
      envFrom:
      - configMapRef:
          name: gunicorn-cm
      ports:
      - containerPort: 8000
